[platformio]
default_envs = nano_old

[env]
platform = atmelavr@5.1.0
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GC9A01A@1.1.0
    adafruit/Adafruit GFX Library@1.11.9

[env:nano_old]
board = nanoatmega328

[env:nano_new]
board = nanoatmega328new
